# -*- mode: ruby -*-
# vi: set ft=ruby :
$script_mysql = <<-SCRIPT
	apt-get update && \
	apt-get install -y mysql-server && \
	mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/jammy64"
  config.vm.network "forwarded_port", guest: 80, host: 8089
  config.vm.network "public_network", ip: "192.168.15.23"
  config.vm.synced_folder "./configs", "/configs"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell",
    inline: "cat /configs/id_jammy.pub >> .ssh/authorized_keys"
  config.vm.provision "shell", inline: $script_mysql
end


